### ISSUE TITLE
Create a class Constants and move all your constants there

### ISSUE THREAD

**Issue by mayisa87** [franciskamara/QuizMaker#1]
https://github.com/franciskamara/QuizMaker/blob/3b7ed0b0ff56d49b10c7d8bf64cbab03ec4f8b73/QuizMaker/Program.cs#L18

Create a class file named Constants and move all your constants there. Define constants for your user input choices and all magic numbers you have.

To use it then everywhere in your code, make them public, like

`public const int MY_CONSTANT = 1;`

**Comment by franciskamara** [comment]
Fixed
