### ISSUE TITLE
Separate ReadLine() and Add

### ISSUE THREAD

**Issue by mayisa87** [franciskamara/QuizMaker#2]
https://github.com/franciskamara/QuizMaker/blob/3b7ed0b0ff56d49b10c7d8bf64cbab03ec4f8b73/QuizMaker/Program.cs#L38

Always keep the separation of Logic and UI in mind. So write a method that handles the user input, the method can even include the for loop, so it creates internally a list of Answers for example and returns it then to Main()

Or... you have a method that reads a single answer and returns the string back and then you add it to the list. But store it before separately in a variable.

Imagine you want to have some kind of input validation later on, then you should definetely have seperate logic of **Reading user input and validate** and **Add it to the list or whatever**

**Comment by franciskamara** [comment]
@mayisa87 Line 74 still has but a List has been created on Line 70
