### ISSUE TITLE
Create UIMethods class and move UI stuff there 

### ISSUE THREAD

**Issue by mayisa87** [franciskamara/QuizMaker#3]
https://github.com/franciskamara/QuizMaker/blob/3b7ed0b0ff56d49b10c7d8bf64cbab03ec4f8b73/QuizMaker/Program.cs#L10-L12

Could be a method, like EmptyUserOutput (like you had in SlotMachine)
https://github.com/franciskamara/QuizMaker/blob/3b7ed0b0ff56d49b10c7d8bf64cbab03ec4f8b73/QuizMaker/Program.cs#L13

Write a method, "ChooseCorrectAnswerIndex" that returns you an integer back.
https://github.com/franciskamara/QuizMaker/blob/3b7ed0b0ff56d49b10c7d8bf64cbab03ec4f8b73/QuizMaker/Program.cs#L42-L43

**Comment by franciskamara** [comment]
Fixed
