### ISSUE TITLE
Create a new class FileUtils and move File related stuff

### ISSUE THREAD

**Issue by mayisa87** [franciskamara/QuizMaker#5]
This can be a method, the parameter can be the content that should be serialized.

https://github.com/franciskamara/QuizMaker/blob/3b7ed0b0ff56d49b10c7d8bf64cbab03ec4f8b73/QuizMaker/Program.cs#L49-L54

**_IMPORTANT:_** Think about what exactly you want to serialize. Is it a single QuestionAndAnswers object or maybe the whole list of questions you first created?

Write a method for deserialize, return for example a List<QuestionAndAnswers>:
https://github.com/franciskamara/QuizMaker/blob/3b7ed0b0ff56d49b10c7d8bf64cbab03ec4f8b73/QuizMaker/Program.cs#L56-L59

You should separate this into a new method and do not use the same "file" variable. Have separated methods with separated variables inside, as for example you could maybe later on have different files where you read and write into!

**Comment by franciskamara** [comment]
@mayisa87 would like to serialise the whole list, but since its in the loop it removes previous entries even if user selects to input more QandA.

Also, should the serialiser and deserialiser be in the same class or seperate?

Moved into a method

**Comment by franciskamara** [comment]
Fixed
